# Generated by Django 4.1.7 on 2023-04-04 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('confirmed_email', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='responsible/unknown.jpg', upload_to='responsible/pictures', verbose_name='Picture profile')),
                ('birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('martial_status', models.CharField(choices=[('S', 'Single'), ('M', 'maried'), ('D', 'Devorced'), ('W', 'widowed'), ('O', 'Others')], default='S', max_length=100)),
                ('adress', models.CharField(blank=True, max_length=100)),
                ('adress2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(choices=[('tana', 'Antananarivo'), ('diego', 'Antsiranana'), ('fianara', 'Fianarantsoa'), ('majunga', 'Mahajanga'), ('tamaga', 'Toamasina'), ('tulear', 'Toliara')], max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('fixe_number', models.CharField(blank=True, max_length=20)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover_letter', models.FileField(upload_to='responsible/cover_letters')),
                ('cv', models.FileField(upload_to='responsible/cv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
