# Generated by Django 4.1.7 on 2023-04-04 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='confirmed_email',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to='responsible/cover_letters'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='cv',
            field=models.FileField(blank=True, upload_to='responsible/cv'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='last_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='martial_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'maried'), ('D', 'Devorced'), ('W', 'widowed'), ('O', 'Others')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
