# Generated by Django 4.1.7 on 2023-04-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('RT', 'Remote')], max_length=50)),
                ('experiences', models.CharField(choices=[('lev1', 'Less than 2 years'), ('lev2', '2 to 5 years'), ('lev3', '5 to 10 years'), ('lev4', 'More than 10 years')], max_length=50)),
                ('summary', models.TextField()),
                ('requierements', models.TextField()),
                ('logo', models.ImageField(blank=True, default='job/unknown.jpg', null=True, upload_to='job')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
